#!/bin/bash

log=test/log
output=test/output

mkdir -p ${output}

cfgs=$1

for cfg in ${cfgs}
do
    echo ${cfg}...
    json=${output}/tmp.json
    out=${output}/${cfg%.jsonnet}.html
    kv=${output}/${cfg%.jsonnet}.kv
    cmp=${log}/${cfg%.jsonnet}.kv
    jsonnet -J . test/${cfg} > ${json}
    ixbrl-reporter ${json} report ixbrl > ${out}
    ixbrl-to-kv ${out} | \
	egrep -v 'VersionProductionSoftware|VersionOfProductionSoftware' | \
	sort > ${kv}
    egrep -v 'VersionProductionSoftware|VersionOfProductionSoftware' ${cmp} | \
	sort | cmp ${kv} -
    if [ $? -ne 0 ]
    then
        echo 'File comparison fail...'
	echo 'diff ${kv} ${cmp} >>>>'
	egrep -v 'VersionProductionSoftware|VersionOfProductionSoftware' \
	      ${cmp} | \
	    sort | cmp ${kv} -
	sort ${cmp} | diff ${kv} -
	exit 1
    fi
done

