
TEMPLATE=example-ct
INPUTS=$(wildcard ${TEMPLATE}/*)

all: example-ct.xhtml

FORCE:

%.xhtml: %.json FORCE
	ixbrl-reporter $< report ixbrl > $@

example-ct.json: ${INPUTS} FORCE
	jsonnet ${TEMPLATE}/${TEMPLATE}.jsonnet -J . -o $@

