
TEMPLATE=example-accts
INPUTS=$(wildcard ${TEMPLATE}/*)

all: example-accts.xhtml

FORCE:

%.xhtml: %.json FORCE
	ixbrl-reporter $< report ixbrl > $@

example-accts.json: ${INPUTS} FORCE
	jsonnet ${TEMPLATE}/${TEMPLATE}.jsonnet -J . -o $@

