
TEMPLATE=example-esef
INPUTS=$(wildcard ${TEMPLATE}/*)

all: esef.xhtml esef-fr.xhtml

%.xhtml: %.json
	ixbrl-reporter $< report ixbrl > $@

esef.json: ${INPUTS} FORCE
	jsonnet ${TEMPLATE}/example.jsonnet -J . -o $@

esef-fr.json: ${INPUTS} FORCE
	jsonnet ${TEMPLATE}/example-fr.jsonnet -J . -o $@
