#!/bin/bash

json2yaml() {
    python -c 'import sys, yaml, json; print(yaml.dump(json.loads(sys.stdin.read())))'
}

JSONNET="jsonnet -J .. -J ../test"

outdir=../../ixbrl-reporter
test=${outdir}/test
taxonomy=${outdir}/taxonomy
report=${outdir}/report

#${JSONNET} template-config.jsonnet | json2yaml > tmp/corptax-config.yaml
#${JSONNET} template-metadata.jsonnet | json2yaml > tmp/metadata-corptax.yaml
#${JSONNET} template-report.jsonnet | json2yaml > tmp/report-corptax.yaml
#${JSONNET} ../lib/style.jsonnet | json2yaml > tmp/style.yaml
#${JSONNET} ../taxonomy/ct-dpl.jsonnet | json2yaml > tmp/ct-dpl.yaml

md() {
    ${JSONNET} ../test/metadata${1}.jsonnet | \
	json2yaml > ${test}/metadata${1}.yaml
}

cfg() {
    ${JSONNET} ${1}.jsonnet | json2yaml > ${test}/${1}.yaml
}

md ''
md '-rev'
md '-acc-aud'
md '-acc-aud-rev'
md '-acc'
md '-acc-rev'
md '-aud'
md '-aud-rev'
md '-esef'
md '-ct'

cfg unaud-micro
cfg unaud-micro-rev
cfg aud-micro
cfg aud-micro-rev
cfg aud-small
cfg aud-small-rev
cfg unaud-abr
cfg unaud-abr-rev
cfg unaud-full
cfg unaud-full-rev
cfg aud-full
cfg aud-full-rev
cfg ct
cfg esef
cfg esef-fr

${JSONNET} ../lib/style.jsonnet | json2yaml > ${test}/../report/style.yaml
${JSONNET} report-unaudited-micro.jsonnet | \
    json2yaml > ${test}/../report/ch/unaudited-micro.yaml
