#!/bin/bash

json2yaml() {
    python -c 'import sys, yaml, json; print(yaml.dump(json.loads(sys.stdin.read())))'
}

JSONNET="jsonnet -J .. -J ../test"

outdir=../../ixbrl-reporter
test=${outdir}/test
taxonomy=${outdir}/taxonomy
report=${outdir}/report

md() {
    ${JSONNET} ../test/metadata${1}.jsonnet | \
	json2yaml > ${test}/metadata${1}.yaml
}

cfg() {
    ${JSONNET} ${1}.jsonnet | json2yaml > ${test}/${1}.yaml
}

md ''
md '-rev'
md '-acc-aud'
md '-acc-aud-rev'
md '-acc'
md '-acc-rev'
md '-aud'
md '-aud-rev'
md '-esef'
md '-ct'

cfg unaud-micro
cfg unaud-micro-rev
cfg aud-micro
cfg aud-micro-rev
cfg aud-small
cfg aud-small-rev
cfg unaud-abr
cfg unaud-abr-rev
cfg unaud-full
cfg unaud-full-rev
cfg aud-full
cfg aud-full-rev
cfg ct
cfg esef
cfg esef-fr

${JSONNET} ../lib/style.jsonnet | json2yaml > ${test}/../report/style.yaml

${JSONNET} ../test/detail/revision-info.jsonnet | \
    json2yaml > ${test}/../revision-info.yaml

# ------

${JSONNET} report-unaudited-micro.jsonnet | \
    json2yaml > ${test}/../report/ch/unaudited-micro.yaml

${JSONNET} report-unaudited-abridged.jsonnet | \
    json2yaml > ${test}/../report/ch/unaudited-abridged.yaml

${JSONNET} report-unaudited-full.jsonnet | \
    json2yaml > ${test}/../report/ch/unaudited-full.yaml

${JSONNET} report-audited-full.jsonnet | \
    json2yaml > ${test}/../report/ch/audited-full.yaml

${JSONNET} report-audited-small.jsonnet | \
    json2yaml > ${test}/../report/ch/audited-small.yaml

${JSONNET} report-audited-micro.jsonnet | \
    json2yaml > ${test}/../report/ch/audited-micro.yaml

${JSONNET} report-esef.jsonnet | \
    json2yaml > ${test}/../report/esef/esef.yaml

${JSONNET} report-esef-fr.jsonnet | \
    json2yaml > ${test}/../report/esef/esef-fr.yaml

${JSONNET} report-ct.jsonnet | \
    json2yaml > ${test}/../report/hmrc/corp-tax.yaml

